name: PacketAddonDrupi
version: ${project.version}
main: me.losin6450.packetaddondrupi.PacketAddonDrupi
authors: [ Losin6450 ]
description: An addon that utilizes protocollibs packet system
depend:
  - ProtocolLib
